
services:

  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image:  semitechnologies/weaviate
    container_name: weaviate
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: unless-stopped
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      -  ollama_data:/root/.ollama
      - ./ollama/entrypoint.sh:/entrypoint.sh
    container_name: ollama
    tty: true
    restart: unless-stopped
    entrypoint: [ "/usr/bin/bash", "/entrypoint.sh" ]

volumes:
  weaviate_data:
  ollama_data:

