
services:

  gitmateai-bot:
    build:
      context: gitmateai-bot
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      APP_ID: "${APP_ID}"
      PRIVATE_KEY: "${PRIVATE_KEY}"
      WEBHOOK_SECRET: "${WEBHOOK_SECRET}"
      GITHUB_CLIENT_ID: "${GITHUB_CLIENT_ID}"
      GITHUB_CLIENT_SECRET: "${GITHUB_CLIENT_SECRET}"
      BACKEND_URL: "${BACKEND_URL:-http://gitmateai-backend:3001/}"
      LLM_API_KEY: "${LLM_API_KEY}"
      LLM_MODEL_NAME: "${LLM_API_NAME:-gpt-4o-mini}"
      PREFIX: "${PREFIX:-gitmateai}"
    restart: unless-stopped

  gitmateai-backend:
    build:
      context: gitmateai-backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_HOST: "${DATABASE_HOST:-weaviate}"
      DATABASE_PORT: "${DATABASE_PORT:-8080}"
      OLLAMA_URL: "${OLLAMA_URL:-http://ollama:11434/}"
      OLLAMA_EMBEDDING_MODEL: "${OLLAMA_EMBEDDING_MODEL:-nomic-embed-text}"
    ports:
      - "3001:3001"

  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.29.0
    ports:
        - "8080:8080"
        - "50051:50051"
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: unless-stopped
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      ENABLE_MODULES: 'text2vec-ollama'
      CLUSTER_HOSTNAME: 'node1'

  ollama:
    image: ollama/ollama:latest
    expose:
      - "11434"
    volumes:
      -  ollama_data:/root/.ollama
      - ./ollama/entrypoint.sh:/entrypoint.sh
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    entrypoint: [ "/usr/bin/bash", "/entrypoint.sh" ]

volumes:
  weaviate_data:
  ollama_data:

