
services:

  gitmate-bot:
    build:
      context: gitmateai-bot
      dockerfile: Dockerfile
    environment:
      BACKEND_URL: "http://gitmate-backend:8080/"
      LLM_API_KEY: "${LLM_API_KEY}"
      LLM_MODEL_NAME: "${LLM_API_NAME:-gpt-4o-mini}"
    restart: unless-stopped


  gitmate-backend:
    build:
      context: gitmateai-backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      PORT: "3001"
      DATABASE_URL: "http://weaviate:8080/"
    expose:
      - "8081"

  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.29.0
    expose:
      - "8080"
      - "50051"
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: unless-stopped
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      ENABLE_MODULES: 'text2vec-ollama'
      CLUSTER_HOSTNAME: 'node1'

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434"
    volumes:
      -  ollama_data:/root/.ollama
      - ./ollama/entrypoint.sh:/entrypoint.sh
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    entrypoint: [ "/usr/bin/bash", "/entrypoint.sh" ]

volumes:
  weaviate_data:
  ollama_data:

